package exporter_test

import (
	"encoding/json"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/stefanriegel/Universal-Token-Assessment/internal/calculator"
)

// fixtureRow mirrors the JSON shape of testdata/cross-source-fixture.json.
// Field names match calculator.FindingRow's JSON tags.
type fixtureRow struct {
	Provider      string `json:"provider"`
	Source        string `json:"source"`
	Region        string `json:"region"`
	Category      string `json:"category"`
	Item          string `json:"item"`
	Count         int    `json:"count"`
	TokensPerUnit int    `json:"tokensPerUnit"`
}

// nativeRateForCategory returns the native (non-NIOS) token rate for a category,
// referencing calculator's exported constants — never hardcoded literals.
func nativeRateForCategory(t *testing.T, category string) int {
	t.Helper()
	switch category {
	case calculator.CategoryDDIObjects:
		return calculator.TokensPerDDIObject
	case calculator.CategoryActiveIPs:
		return calculator.TokensPerActiveIP
	case calculator.CategoryManagedAssets:
		return calculator.TokensPerManagedAsset
	default:
		t.Fatalf("unknown category %q in fixture", category)
		return 0
	}
}

// loadCrossSourceFixture reads the shared fixture and maps it to calculator.FindingRow,
// deriving TokensPerUnit from calculator's native rate constants (not the JSON field,
// which exists for readability/cross-language parity only).
func loadCrossSourceFixture(t *testing.T) []calculator.FindingRow {
	t.Helper()
	data, err := os.ReadFile("../../testdata/cross-source-fixture.json")
	if err != nil {
		t.Fatalf("failed to read shared cross-source fixture: %v", err)
	}
	var rows []fixtureRow
	if err := json.Unmarshal(data, &rows); err != nil {
		t.Fatalf("failed to unmarshal cross-source fixture: %v", err)
	}

	findings := make([]calculator.FindingRow, 0, len(rows))
	for _, r := range rows {
		rate := nativeRateForCategory(t, r.Category)
		findings = append(findings, calculator.FindingRow{
			Provider:      r.Provider,
			Source:        r.Source,
			Region:        r.Region,
			Category:      r.Category,
			Item:          r.Item,
			Count:         r.Count,
			TokensPerUnit: rate,
		})
	}
	return findings
}

// expectedGrandTotal hand-derives the spec formula (aggregate-then-divide per
// category, then SUM the three category totals) directly from the raw fixture
// rows, independent of calculator.Calculate.
func expectedGrandTotal(t *testing.T, findings []calculator.FindingRow) int {
	t.Helper()
	var totalDDI, totalIP, totalAsset int
	for _, f := range findings {
		switch f.Category {
		case calculator.CategoryDDIObjects:
			totalDDI += f.Count
		case calculator.CategoryActiveIPs:
			totalIP += f.Count
		case calculator.CategoryManagedAssets:
			totalAsset += f.Count
		}
	}
	ddiTokens := calculator.CeilDiv(totalDDI, calculator.TokensPerDDIObject)
	ipTokens := calculator.CeilDiv(totalIP, calculator.TokensPerActiveIP)
	assetTokens := calculator.CeilDiv(totalAsset, calculator.TokensPerManagedAsset)
	return ddiTokens + ipTokens + assetTokens
}

// TestCrossSourceAgreement proves that the Scan calculator, the exported XLSX
// Grand Total cell, and (in cross-source.test.ts) the Sizer all agree on the
// same total for the shared testdata/cross-source-fixture.json, computed
// independently via the spec formula (aggregate-then-divide-then-SUM) as the
// oracle -- no live-engine import, no golden-master fixture.
func TestCrossSourceAgreement(t *testing.T) {
	findings := loadCrossSourceFixture(t)
	want := expectedGrandTotal(t, findings)

	// Scan path.
	got := calculator.Calculate(findings).GrandTotal
	if got != want {
		t.Fatalf("Scan GrandTotal = %d, want %d (spec-derived)", got, want)
	}

	// XLSX export path: build the workbook and read the Grand Total back off
	// the generated bytes (D-04) -- never assert against the in-memory
	// TokenResult.
	f := openResult(t, testInput(findings, nil))

	// Grand Total value lives in Summary!B2 (SetRow("A2", {label, value}) puts
	// the label in A2 and the value in the next cell, B2); verified empirically
	// against exporter.go's buildSummarySheet.
	cell, err := f.GetCellValue("Summary", "B2")
	if err != nil {
		t.Fatalf("failed to read Summary!B2: %v", err)
	}
	// Strip thousands separators defensively (Grand Total here is 1023, which
	// crosses the 1000 boundary and exercises the separator format).
	cell = strings.ReplaceAll(cell, ",", "")
	xlsxTotal, err := strconv.Atoi(cell)
	if err != nil {
		t.Fatalf("failed to parse Summary!B2 value %q: %v", cell, err)
	}
	if xlsxTotal != want {
		t.Fatalf("XLSX Grand Total = %d, want %d (spec-derived)", xlsxTotal, want)
	}
}
